function embaralhar() {
    const div0 = document.querySelector('#div0')
    const div1 = document.querySelector('#div1')
    const div2 = document.querySelector('#div2')
    const div3 = document.querySelector('#div3')
    const div4 = document.querySelector('#div4')
    const div5 = document.querySelector('#div5')
    const div6 = document.querySelector('#div6')
    const div7 = document.querySelector('#div7')
    const div8 = document.querySelector('#div8')
    const div9 = document.querySelector('#div9')
    const div10 = document.querySelector('#div10')
    const div11 = document.querySelector('#div11')
    const div12 = document.querySelector('#div12')
    const div13 = document.querySelector('#div13')
    const div14 = document.querySelector('#div14')
    const div15 = document.querySelector('#div15')
    let a = div0.style.order = Math.floor(Math.random() * 17)
    let b = div1.style.order = Math.floor(Math.random() * 13)
    let c = div2.style.order = Math.floor(Math.random() * 12)
    let d = div3.style.order = Math.floor(Math.random() * 17)
    let e = div4.style.order = Math.floor(Math.random() * 17)
    let f = div5.style.order = Math.floor(Math.random() * 17)
    let g = div6.style.order = Math.floor(Math.random() * 17)
    let h = div7.style.order = Math.floor(Math.random() * 17)
    let i = div8.style.order = Math.floor(Math.random() * 17)
    let j = div9.style.order = Math.floor(Math.random() * 17)
    let k = div10.style.order = Math.floor(Math.random() * 17)
    let l = div11.style.order = Math.floor(Math.random() * 17)
    let m = div12.style.order = Math.floor(Math.random() * 17)
    let n = div13.style.order = Math.floor(Math.random() * 17)
    let o = div14.style.order = Math.floor(Math.random() * 17)
    let p = div15.style.order = Math.floor(Math.random() * 17)
    console.log(a,b,c,d)
}
embaralhar()